name: "Terraform Plan"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'warning'
        type: choice
        options:
          - prod

env:
  TF_CLOUD_ORGANIZATION: "quantum2025"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "wsp-init-provisioning"
  CONFIG_DIRECTORY: "./terraform"

jobs:
  terraform:
    if: github.repository == 'oayras/node-postgres-crud-api'
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate terraform.tfvars
        run: |
          cat << EOF > terraform/terraform.tfvars
          repoName = "${{ github.event.repository.name }}"
          appPort = "${{ vars.APP_PORT }}"
          alb_name = "${{ vars.AWS_ALB_NAME }}"
          aws_region = "${{ vars.AWS_REGION }}"
          cloudwatch_loggroup = "${{ vars.AWS_LOG_GROUP }}"
          execution_role_arn = "${{ vars.AWS_EXECUTION_ROLE }}"
          fqdn = "${{ vars.APP_FQDN }}"
          environment = "${{ inputs.environment }}"
          image =  "${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:${{ github.sha }}"
          EOF

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: plan-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}
          speculative: true

      - name: Create Plan Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: plan-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.plan-upload.outputs.configuration_version_id }}
          plan_only: true

      - name: Get Plan Output
        uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.0.0
        id: plan-output
        with:
          plan: ${{ fromJSON(steps.plan-run.outputs.payload).data.relationships.plan.data.id }}